site_name: SMS Docs
theme:
    features:
        navigation.tabs  # instant, tabs 
    name: 'material'
    logo: img/mortarboard.svg
    palette:
        scheme: default # default, slate
        primary: green # red, pink, purple, deep purple, indigo, blue, light blue, cyan,teal,
                       # green,light green,lime,yellow,amber,orange,deep orange,brown,grey,blue grey,black,white
        
nav:
    - Home: index.md
    - Modules: 
        - School Admin: modules/school-admin.md
        - Student Management: modules/student-management.md
        - User Management: modules/user-management.md
    - System Architecture: architecture.md
    
