site_name: SMS Docs
extra:
    version:
        provider: mike 
theme:

    features:
        navigation.instant   
    name: 'material'
    logo: img/mortarboard.svg
    palette:
        scheme: default # default, slate
        primary: green # red, pink, purple, deep purple, indigo, blue, light blue, cyan,teal,
                    # green,light green,lime,yellow,amber,orange,deep orange,brown,grey,blue grey,black,white
        
nav:
    - Overview: index.md
    - Features: features.md
    
